// Shared render core used by BOTH the CGI entry (server.tsx) and the
// resident FastCGI server (server-main.tsx). Keeping the HTML assembly in
// one place guarantees the two entry points emit byte-identical markup.
// This module never ships to the browser, so referencing process is safe.
//
// Rendering is streaming (renderToPipeableStream): the document head is
// flushed immediately and lazy/Suspense sections arrive in later chunks,
// which is what makes the resident server's TTFB small on slow renderers.

import { renderToPipeableStream } from "react-dom/server";
import { StaticRouter } from "react-router";
import { Transform } from "stream";
import { App, type AppProps } from "../App";
import type { Params, RenderMode } from "../types";
export { isRenderMode } from "../types";
// Tailwind v4 output (generated by build-ssr.sh from styles/main.css),
// compiled to a string so the SSR <head> stays self-contained.
// The ?raw suffix makes Vite's dev SSR pipeline return the file text too
// (plain *.css imports are side-effect modules there — default undefined),
// while esbuild matches it via --loader:.css?raw=text.
import styles from "../tailwind.css?raw";

// Content hash of the client bundle, injected at build time by
// scripts/build-ssr.sh (esbuild `--define:BUNDLE_QUERY="<hash>"`). Declared
// here so tsc accepts the identifier; the `typeof` guard below keeps the
// Vite dev SSR pipeline - which never defines it - from throwing a
// ReferenceError while rendering.
declare const BUNDLE_QUERY: string;

// The bundle is served from a stable path (/js/react-ssr.js) but its bytes
// change on every rebuild, and a URL that never changes is a cache key that
// never changes: a browser holding the previous copy keeps serving it,
// revalidation bug or not. Appending this build's content hash makes every
// new document reference a URL the client has never stored, so a stale
// entry can no longer be picked up at all. Dev mode yields the plain path.
export function bundleSrc(): string {
  const hash = typeof BUNDLE_QUERY !== "undefined" ? BUNDLE_QUERY : "";
  return hash ? `/js/react-ssr.js?v=${hash}` : "/js/react-ssr.js";
}

// Everything inlined into <script>window.__SSR_DATA__</script>. The client
// bundle must be able to reconstruct the exact same values for hydration.
export interface RenderData {
  params: Params;
  method: string;
  serverTime: string;
  nodeVersion: string;
  mode: RenderMode;
}

export { type RenderMode };

export function parseQuery(query: string): Params {
  const params: Params = {};
  if (!query) return params;
  for (const pair of query.split("&")) {
    if (!pair) continue;
    const eq = pair.indexOf("=");
    const rawKey = eq >= 0 ? pair.slice(0, eq) : pair;
    const rawValue = eq >= 0 ? pair.slice(eq + 1) : "";
    try {
      const key = decodeURIComponent(rawKey.replace(/\+/g, " "));
      const value = decodeURIComponent(rawValue.replace(/\+/g, " "));
      params[key] = value;
    } catch {
      // ignore malformed pairs
    }
  }
  return params;
}

// Value can only originate from the server side (this module is never
// bundled for the browser), so calling process.version here is safe and is
// the reason hydration in the client bundle never touches `process`.
export function buildData(
  params: Params,
  method: string,
  mode: RenderMode
): RenderData {
  return {
    params,
    method,
    serverTime: new Date().toLocaleString("en-GB", {
      dateStyle: "medium",
      timeStyle: "medium",
    }),
    nodeVersion: process.version,
    mode,
  };
}

// JSON.stringify is safe against "</script>" because React escapes string
// values during renderToString, but the blob below is raw JS text; escape
// "<" so a hostile param cannot break out of the script element.
export const safeJson = (obj: RenderData): string => JSON.stringify(obj).replace(/</g, "\\u003c");

// Everything up to (not including) the App markup. `renderHead` + streamed
// markup + `renderTail` reconstruct the exact same document renderPage
// buffers — so cached pages and streamed pages stay byte-identical.
export function renderHead(mode: RenderMode): string {
  const title =
    mode === "csr"
      ? "React Router CSR via AgentHTTPD"
      : "React Router SSR via AgentHTTPD";
  return `<!DOCTYPE html>
<html lang="en" class="bg-ink">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>${title}</title>
<style>${styles}</style>
</head>
<body>
<div id="root">`;
}

// The streaming client bundle is an ES module (route chunks are dynamic
// imports), so it must be loaded with type="module".
export function renderTail(data: RenderData): string {
  return `</div>
<script>window.__SSR_DATA__ = ${safeJson(data)};</script>
<script type="module" src="${bundleSrc()}"></script>
</body>
</html>
`;
}

// A CSR request performs zero server React work: empty shell only.
// The <noscript> goes BEFORE #root so the root div is truly empty
// (createRoot needs a clean mount point with no children).
function csrShell(mode: RenderMode, data: RenderData): string {
  const title =
    mode === "csr"
      ? "React Router CSR via AgentHTTPD"
      : "React Router SSR via AgentHTTPD";
  return `<!DOCTYPE html>
<html lang="en" class="bg-ink">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>${title}</title>
<style>${styles}</style>
</head>
<body>
<noscript><p class="mx-auto max-w-3xl px-5 py-10">This page needs JavaScript enabled (client-side rendering mode).</p></noscript>
<div id="root"></div>
<script>window.__SSR_DATA__ = ${safeJson(data)};</script>
<script type="module" src="${bundleSrc()}"></script>
</body>
</html>
`;
}

// Stream one SSR document. `onChunk` receives the head, the App markup (in
// possibly several segments while React resolves Suspense/lazy), then the
// tail. Resolves with the FULL document once complete — the resident server
// uses onChunk for TTFB (head flushes first) and the resolved string as its
// ISR cache entry, so one render serves both goals.
export function renderStream(
  params: Params,
  method: string,
  pathname: string,
  mode: RenderMode,
  onChunk: (chunk: string) => void
): Promise<string> {
  const data = buildData(params, method, mode);
  if (mode === "csr") {
    const shell = csrShell(mode, data);
    onChunk(shell);
    return Promise.resolve(shell);
  }
  return new Promise((resolve, reject) => {
    const head = renderHead(mode);
    const body: string[] = [];
    onChunk(head);
    const { pipe, abort } = renderToPipeableStream(
      <StaticRouter location={pathname || "/react"}>
        <App {...data} />
      </StaticRouter>,
      {
        onShellError(err) {
          abort();
          reject(err instanceof Error ? err : new Error(String(err)));
        },
      }
    );
    const out = new Transform({
      transform(chunk: Buffer, _enc, cb) {
        const text = chunk.toString("utf8");
        body.push(text);
        try {
          onChunk(text);
          cb();
        } catch (e) {
          cb(e as Error);
        }
      },
    });
    // onAllReady fires when React is done emitting, but the Transform may
    // still be flushing the last chunks. Wait for 'finish' so the cache
    // stores the COMPLETE document (head + all body + tail).
    out.on("finish", () => {
      try {
        const tail = renderTail(data);
        onChunk(tail);
        resolve(head + body.join("") + tail);
      } catch (e) {
        reject(e);
      }
    });
    out.on("error", (err) => {
      abort();
      reject(err instanceof Error ? err : new Error(String(err)));
    });
    pipe(out);
  });
}

// Buffered variant (CGI entry + ISR cache fill): collect the stream into one
// string. Identical bytes to the streamed document.
export async function renderPage(
  params: Params,
  method: string,
  pathname: string,
  mode: RenderMode = "ssr"
): Promise<string> {
  const chunks: string[] = [];
  await renderStream(params, method, pathname, mode, (c) => chunks.push(c));
  return chunks.join("");
}